;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Type.Aim",DevComment="瞄准")
+GameplayTagList=(Tag="Ability.Type.Attack",DevComment="攻击类")
+GameplayTagList=(Tag="Ability.Type.Attack.AimShot",DevComment="瞄准射击攻击")
+GameplayTagList=(Tag="Ability.Type.Attack.Heavy",DevComment="重击")
+GameplayTagList=(Tag="Ability.Type.Attack.Normal",DevComment="普通攻击")
+GameplayTagList=(Tag="Ability.Type.Attack.Plunging",DevComment="下落攻击")
+GameplayTagList=(Tag="Ability.Type.Climb",DevComment="攀爬")
+GameplayTagList=(Tag="Ability.Type.ClimbJump",DevComment="攀爬跳跃")
+GameplayTagList=(Tag="Ability.Type.Dash",DevComment="冲刺")
+GameplayTagList=(Tag="Ability.Type.Die",DevComment="死亡")
+GameplayTagList=(Tag="Ability.Type.Dodge",DevComment="闪避")
+GameplayTagList=(Tag="Ability.Type.FastSwim",DevComment="快速游泳")
+GameplayTagList=(Tag="Ability.Type.Glide",DevComment="滑翔")
+GameplayTagList=(Tag="Ability.Type.Hook",DevComment="勾住钩索")
+GameplayTagList=(Tag="Ability.Type.Interaction",DevComment="交互 (拾取、对话等)")
+GameplayTagList=(Tag="Ability.Type.IsInAir",DevComment="空中能力")
+GameplayTagList=(Tag="Ability.Type.Jump",DevComment="跳跃")
+GameplayTagList=(Tag="Ability.Type.Passive",DevComment="被动技能")
+GameplayTagList=(Tag="Ability.Type.Revive",DevComment="复活")
+GameplayTagList=(Tag="Ability.Type.Skill.Elemental",DevComment="元素战技")
+GameplayTagList=(Tag="Ability.Type.Sprint",DevComment="冲刺")
+GameplayTagList=(Tag="Ability.Type.Swap.In",DevComment="角色切入")
+GameplayTagList=(Tag="Ability.Type.Swap.Out",DevComment="角色切出")
+GameplayTagList=(Tag="Ability.Type.Swim",DevComment="游泳")
+GameplayTagList=(Tag="Ability.Type.Ultimate",DevComment="终极技能/元素爆发")
+GameplayTagList=(Tag="Ability.Type.Walk",DevComment="行走")
+GameplayTagList=(Tag="Character.Attribute.Stamina.Exhausted",DevComment="体力耗尽")
+GameplayTagList=(Tag="Character.Event.Aim.Start",DevComment="玩家按下了瞄准键")
+GameplayTagList=(Tag="Character.Event.Aim.Stop",DevComment="玩家按下了取消瞄准键")
+GameplayTagList=(Tag="Character.Event.AirStateChanged",DevComment="空中状态改变")
+GameplayTagList=(Tag="Character.Event.Attack.AimShot",DevComment="玩家按下：瞄准射击攻击")
+GameplayTagList=(Tag="Character.Event.Attack.AimShot.Start",DevComment="瞄准射击开始")
+GameplayTagList=(Tag="Character.Event.Attack.AimShot.Stop",DevComment="瞄准射击结束")
+GameplayTagList=(Tag="Character.Event.Attack.Heavy",DevComment="玩家按下：重击")
+GameplayTagList=(Tag="Character.Event.Attack.Normal",DevComment="玩家按下：普通攻击")
+GameplayTagList=(Tag="Character.Event.Attack.Plunge",DevComment="玩家按下：下落攻击")
+GameplayTagList=(Tag="Character.Event.BaseMove",DevComment="玩家按下：基础移动")
+GameplayTagList=(Tag="Character.Event.CheckHeavyBranch",DevComment="检查玩家是否仍在按住普攻键，若是则模拟发送重击输入")
+GameplayTagList=(Tag="Character.Event.Climb.Start",DevComment="进入攀爬")
+GameplayTagList=(Tag="Character.Event.Climb.Stop",DevComment="退出攀爬")
+GameplayTagList=(Tag="Character.Event.ClimbJump",DevComment="角色攀爬跳跃")
+GameplayTagList=(Tag="Character.Event.Dash",DevComment="玩家按下了闪避键")
+GameplayTagList=(Tag="Character.Event.Die",DevComment="角色死亡")
+GameplayTagList=(Tag="Character.Event.Glide.Start",DevComment="玩家按下: 跳跃")
+GameplayTagList=(Tag="Character.Event.Glide.Stop",DevComment="玩家按下：跳跃（结束）")
+GameplayTagList=(Tag="Character.Event.Hook.Start",DevComment="玩家按下：勾住钩索")
+GameplayTagList=(Tag="Character.Event.Hook.Stop",DevComment="玩家按下：停止勾住钩索")
+GameplayTagList=(Tag="Character.Event.Interact",DevComment="玩家按下: 交互")
+GameplayTagList=(Tag="Character.Event.Jump.Start",DevComment="玩家按下：跳跃（开始）")
+GameplayTagList=(Tag="Character.Event.Jump.Stop",DevComment="玩家按下：跳跃（结束）")
+GameplayTagList=(Tag="Character.Event.PlungeAttackLanded",DevComment="下落攻击落地")
+GameplayTagList=(Tag="Character.Event.Revive",DevComment="角色复活")
+GameplayTagList=(Tag="Character.Event.Sprint.Start",DevComment="冲刺开始")
+GameplayTagList=(Tag="Character.Event.Sprint.Start.Long",DevComment="长疾跑开始")
+GameplayTagList=(Tag="Character.Event.Sprint.Start.Short",DevComment="短疾跑开始")
+GameplayTagList=(Tag="Character.Event.Sprint.Stop",DevComment="冲刺结束")
+GameplayTagList=(Tag="Character.Event.Swap.In",DevComment="角色切入")
+GameplayTagList=(Tag="Character.Event.Swap.Out",DevComment="角色切出")
+GameplayTagList=(Tag="Character.Event.Walk",DevComment="行走开始")
+GameplayTagList=(Tag="Character.Event.Walk.Start",DevComment="行走开始")
+GameplayTagList=(Tag="Character.Event.Walk.Stop",DevComment="行走结束")
+GameplayTagList=(Tag="Character.Playable.Carlotta",DevComment="珂莱塔")
+GameplayTagList=(Tag="Character.Playable.GongSunLi",DevComment="公孙离")
+GameplayTagList=(Tag="Character.Playable.Lumine",DevComment="荧")
+GameplayTagList=(Tag="Character.Playable.Manageress",DevComment="女管理员")
+GameplayTagList=(Tag="Character.Playable.Mita",DevComment="米塔")
+GameplayTagList=(Tag="Character.Playable.Saber",DevComment="Saber")
+GameplayTagList=(Tag="Character.Playable.Stelle",DevComment="星")
+GameplayTagList=(Tag="Character.Playable.YiXuan",DevComment="仪玄")
+GameplayTagList=(Tag="Character.State.Aiming",DevComment="正在瞄准")
+GameplayTagList=(Tag="Character.State.Alive",DevComment="角色存活")
+GameplayTagList=(Tag="Character.State.Attacking",DevComment="正在攻击")
+GameplayTagList=(Tag="Character.State.Attacking.Heavy",DevComment="正在攻击  - 重击")
+GameplayTagList=(Tag="Character.State.Attacking.Normal",DevComment="正在攻击  - 普通攻击")
+GameplayTagList=(Tag="Character.State.Attacking.Plunging",DevComment="正在攻击  - 下落攻击")
+GameplayTagList=(Tag="Character.State.Blocking",DevComment="正在格挡")
+GameplayTagList=(Tag="Character.State.CanCombo",DevComment="可以连击")
+GameplayTagList=(Tag="Character.State.Casting",DevComment="正在施法/吟唱 (持续性技能)")
+GameplayTagList=(Tag="Character.State.Climbing",DevComment="在攀爬")
+GameplayTagList=(Tag="Character.State.ClimbJumping",DevComment="在攀爬跳跃")
+GameplayTagList=(Tag="Character.State.ClimbStartTransition",DevComment="在开始上墙攀爬")
+GameplayTagList=(Tag="Character.State.Dashing",DevComment="在冲刺/闪避中")
+GameplayTagList=(Tag="Character.State.Dead",DevComment="角色死亡")
+GameplayTagList=(Tag="Character.State.FastSwimming",DevComment="在快速游泳")
+GameplayTagList=(Tag="Character.State.Frozen",DevComment="被冰冻 (无法控制)")
+GameplayTagList=(Tag="Character.State.Grounded",DevComment="在地面")
+GameplayTagList=(Tag="Character.State.Hooking",DevComment="正在勾住钩索")
+GameplayTagList=(Tag="Character.State.InAir",DevComment="在空中 (跳跃或下落)")
+GameplayTagList=(Tag="Character.State.InAir.Airborne",DevComment="在空中")
+GameplayTagList=(Tag="Character.State.InAir.Falling",DevComment="在下落")
+GameplayTagList=(Tag="Character.State.InAir.Gliding",DevComment="在滑翔")
+GameplayTagList=(Tag="Character.State.InAir.Jumping",DevComment="在跳跃")
+GameplayTagList=(Tag="Character.State.InStandby",DevComment="角色处于待机状态")
+GameplayTagList=(Tag="Character.State.Invincible",DevComment="处于无敌状态 (如闪避的无敌帧、大招动画)")
+GameplayTagList=(Tag="Character.State.Reviving",DevComment="在复活")
+GameplayTagList=(Tag="Character.State.Sprinting",DevComment="在冲刺")
+GameplayTagList=(Tag="Character.State.Stunned",DevComment="被眩晕 (无法控制)")
+GameplayTagList=(Tag="Character.State.Swapping",DevComment="在切入")
+GameplayTagList=(Tag="Character.State.Swapping.In",DevComment="在切入")
+GameplayTagList=(Tag="Character.State.Swapping.Out",DevComment="在切出")
+GameplayTagList=(Tag="Character.State.Swimming",DevComment="在游泳")
+GameplayTagList=(Tag="Character.State.Uncontrollable",DevComment="角色当前不可控制")
+GameplayTagList=(Tag="Character.State.Unswitchable",DevComment="角色不可切换")
+GameplayTagList=(Tag="Character.State.Walking",DevComment="在行走")
+GameplayTagList=(Tag="Damage.Source.AreaOfEffect",DevComment="伤害来源: 范围效果 (AOE)")
+GameplayTagList=(Tag="Damage.Source.Melee",DevComment="伤害来源: 近战")
+GameplayTagList=(Tag="Damage.Source.Ranged",DevComment="伤害来源: 远程")
+GameplayTagList=(Tag="Damage.Type.Elemental.Anemo",DevComment="伤害类型: 元素 - 风")
+GameplayTagList=(Tag="Damage.Type.Elemental.Cryo",DevComment="伤害类型: 元素 - 冰")
+GameplayTagList=(Tag="Damage.Type.Elemental.Dendro",DevComment="伤害类型: 元素 - 草")
+GameplayTagList=(Tag="Damage.Type.Elemental.Electro",DevComment="伤害类型: 元素 - 雷")
+GameplayTagList=(Tag="Damage.Type.Elemental.Geo",DevComment="伤害类型: 元素 - 岩")
+GameplayTagList=(Tag="Damage.Type.Elemental.Hydro",DevComment="伤害类型: 元素 - 水")
+GameplayTagList=(Tag="Damage.Type.Elemental.Pyro",DevComment="伤害类型: 元素 - 火")
+GameplayTagList=(Tag="Damage.Type.Physical",DevComment="伤害类型: 物理")
+GameplayTagList=(Tag="Damage.Type.True",DevComment="伤害类型: 真实伤害 (无视防御)")
+GameplayTagList=(Tag="Effect.Buff.AttackUp",DevComment="增益效果: 攻击力提升")
+GameplayTagList=(Tag="Effect.Buff.DamageImmunity",DevComment="增益效果: 伤害免疫")
+GameplayTagList=(Tag="Effect.Buff.DefenseUp",DevComment="增益效果: 防御力提升")
+GameplayTagList=(Tag="Effect.Buff.SpeedUp",DevComment="增益效果: 移动速度提升")
+GameplayTagList=(Tag="Effect.Control.Knockback",DevComment="控制效果: 击退")
+GameplayTagList=(Tag="Effect.Control.Launch",DevComment="控制效果: 击飞")
+GameplayTagList=(Tag="Effect.Control.Pull",DevComment="控制效果: 拉近")
+GameplayTagList=(Tag="Effect.Control.Stun",DevComment="控制效果: 眩晕")
+GameplayTagList=(Tag="Effect.Status.Burning",DevComment="状态异常: 燃烧 (持续掉血)")
+GameplayTagList=(Tag="Effect.Status.Poisoned",DevComment="状态异常: 中毒")
+GameplayTagList=(Tag="Effect.Status.Rooted",DevComment="状态异常: 定身")
+GameplayTagList=(Tag="Effect.Status.Silenced",DevComment="状态异常: 沉默 (不能使用技能)")
+GameplayTagList=(Tag="Effect.Status.Slowed",DevComment="状态异常: 减速")
+GameplayTagList=(Tag="Event.Montage.Aim.Start",DevComment="进入瞄准动画")
+GameplayTagList=(Tag="Event.Montage.Attack.End",DevComment="攻击蒙太奇结束")
+GameplayTagList=(Tag="Event.Montage.Attack.Start",DevComment="攻击蒙太奇开始")
+GameplayTagList=(Tag="Event.Montage.ComboWindow.Close",DevComment="连招窗口关闭")
+GameplayTagList=(Tag="Event.Montage.ComboWindow.Open",DevComment="连招窗口打开")
+GameplayTagList=(Tag="Event.Montage.Damage.Deal",DevComment="伤害处理时刻")
+GameplayTagList=(Tag="UI.Event.AimStar.Hide",DevComment="准星隐藏")
+GameplayTagList=(Tag="UI.Event.AimStar.Show",DevComment="准星显示")
+GameplayTagList=(Tag="UI.Type.Menu.CloseGame",DevComment="关闭游戏面板")
+GameplayTagList=(Tag="UI.Type.Menu.Inventory",DevComment="背包界面")
+GameplayTagList=(Tag="UI.Type.Menu.Login",DevComment="登录界面")
+GameplayTagList=(Tag="UI.Type.Menu.Player",DevComment="玩家面板")
+GameplayTagList=(Tag="UI.Type.Menu.PlayerCharacterManager",DevComment="玩家角色管理器")
+GameplayTagList=(Tag="UI.Type.Menu.StartGame",DevComment="开始游戏界面")
+GameplayTagList=(Tag="UI.Type.Menu.TeamManager",DevComment="队伍管理器界面")
+GameplayTagList=(Tag="Weapon.Event.GoBack",DevComment="武器回到背上")
+GameplayTagList=(Tag="Weapon.Event.SetUp",DevComment="设置角色武器")
+GameplayTagList=(Tag="Weapon.Type.Gun.Rifle",DevComment="武器类型：步枪")
+GameplayTagList=(Tag="Weapon.Type.Sword",DevComment="武器类型：剑")

